apiVersion: v2
name: alpha-crm
description: Alpha CRM umbrella Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://charts/backend"